#!/usr/bin/env node

/**
 * App Setup Wizard
 * Interactive setup for M-Pesa credentials and configuration
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

console.log(`
🚀 APP SETUP WIZARD
================================

This wizard will help you configure your M-Pesa Daraja API credentials.

BEFORE YOU START:
1. Create an account at https://developer.safaricom.co.ke/
2. Create a new app and get your Consumer Key & Secret
3. Get your Business Short Code and Passkey from Test Credentials
4. Have your callback URL ready (use ngrok for local development)

Press Enter to continue...
`);

function askQuestion(question) {
    return new Promise((resolve) => {
        rl.question(question, (answer) => {
            resolve(answer.trim());
        });
    });
}

async function setupWizard() {
    try {
        await askQuestion('Press Enter to continue...');
        
        console.log('\n📱 M-PESA CONFIGURATION\n');
        
        const consumerKey = await askQuestion('Enter your Consumer Key: ');
        const consumerSecret = await askQuestion('Enter your Consumer Secret: ');
        const businessShortCode = await askQuestion('Enter your Business Short Code (or press Enter for sandbox default): ') || '174379';
        const passkey = await askQuestion('Enter your Passkey: ');
        
        console.log('\n🌐 CALLBACK CONFIGURATION\n');
        console.log('For local development, use ngrok:');
        console.log('1. Install ngrok: npm install -g ngrok');
        console.log('2. Run: ngrok http 3000');
        console.log('3. Copy the https URL (e.g., https://abc123.ngrok.io)\n');
        
        const callbackUrl = await askQuestion('Enter your callback URL: ');
        const environment = await askQuestion('Environment (sandbox/production) [sandbox]: ') || 'sandbox';
        
        // Create .env file
        const envContent = `# M-Pesa Daraja API Configuration
# Generated by setup wizard


PORT=3000
NODE_ENV=development
`;

        fs.writeFileSync('.env', envContent);
        
        console.log('\n✅ SETUP COMPLETE!\n');
        console.log('Created .env file with your configuration.');
        console.log('\nNEXT STEPS:');
        console.log('1. Start the server: npm run dev');
        console.log('2. Open browser: https://kopesha.mkopaji.com:3004');
        console.log('3. Test with a small amount (1-100 KSh)');
        console.log('4. Use test phone numbers from Daraja Portal');
        console.log('\nTROUBLESHOOTING:');
        console.log('- Ensure callback URL is publicly accessible');
        console.log('- Check Daraja Portal for transaction logs');
        console.log('- Verify credentials are for correct environment');
        console.log('\nSupport: Check docs/README.md for detailed instructions\n');
        
    } catch (error) {
        console.error('❌ Setup failed:', error.message);
    } finally {
        rl.close();
    }
}

// Check if .env already exists
if (fs.existsSync('.env')) {
    console.log('⚠️  .env file already exists!');
    rl.question('Do you want to overwrite it? (y/N): ', (answer) => {
        if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
            setupWizard();
        } else {
            console.log('Setup cancelled. Existing .env file preserved.');
            rl.close();
        }
    });
} else {
    setupWizard();
}